const std = @import("std");
const zfh = @import("zig_files_hash");
const def = @import("def.zig");
const common = @import("common.zig");

const writeMessageFromCamel = common.writeMessageFromCamel;
const writeSnake = common.writeSnake;

pub fn render(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\// Generated by tools/c_api/gen.zig. Do not edit by hand.
        \\const zfh = @import("root.zig");
        \\
        \\
    );

    try w.print("pub const ZFH_API_VERSION: u32 = {d};\n\n", .{def.api_version});

    try renderZigErrorEnum(w);
    try renderZigAlgorithmEnum(w);
    try renderZigOptionFlags(w);
    try renderToHashAlgorithm(w);
    try renderErrorMessage(w);
    try renderMapLibraryError(w);
}

fn renderZigErrorEnum(w: *std.Io.Writer) !void {
    try w.writeAll("pub const zfh_error = enum(c_int) {\n");

    for (def.error_prefix, 0..) |entry, value| {
        try w.print("    {s} = {d},\n", .{ entry.zig_name, value });
    }

    inline for (std.meta.fields(zfh.Error), 0..) |field, i| {
        try w.writeAll("    ");
        try writeSnake(w, field.name, .lower, .camel);
        try w.print(" = {d},\n", .{def.error_prefix.len + i});
    }

    const suffix_offset = def.error_prefix.len + std.meta.fields(zfh.Error).len;
    for (def.error_suffix, 0..) |entry, i| {
        try w.print("    {s} = {d},\n", .{ entry.zig_name, suffix_offset + i });
    }

    try w.writeAll("    _,\n};\n\n");
}

fn renderZigAlgorithmEnum(w: *std.Io.Writer) !void {
    try w.writeAll("pub const zfh_algorithm = enum(c_int) {\n");
    inline for (std.meta.fields(zfh.HashAlgorithm), 0..) |field, value| {
        try w.writeAll("    ");
        try writeSnake(w, field.name, .lower, .separators);
        try w.print(" = {d},\n", .{value});
    }
    try w.writeAll("    _,\n};\n\n");
}

fn renderZigOptionFlags(w: *std.Io.Writer) !void {
    for (def.option_flags) |entry| {
        try w.print("pub const {s}: u32 = {s};\n", .{ entry.zig_name, entry.expr });
    }
    try w.writeByte('\n');
}

fn renderToHashAlgorithm(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\pub fn toHashAlgorithm(alg: zfh_algorithm) ?zfh.HashAlgorithm {
        \\    return switch (alg) {
        \\
    );
    inline for (std.meta.fields(zfh.HashAlgorithm)) |field| {
        try w.writeAll("        .");
        try writeSnake(w, field.name, .lower, .separators);
        try w.print(" => .{f},\n", .{std.zig.fmtId(field.name)});
    }
    try w.writeAll(
        \\        else => null,
        \\    };
        \\}
        \\
        \\
    );
}

fn renderErrorMessage(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\pub fn errorMessage(code: zfh_error) [*:0]const u8 {
        \\    return switch (code) {
        \\
    );

    for (def.error_prefix) |entry| {
        try renderZigErrorMessageCase(w, entry.zig_name, entry.message);
    }

    inline for (std.meta.fields(zfh.Error)) |field| {
        try w.writeAll("        .");
        try writeSnake(w, field.name, .lower, .camel);
        try w.writeAll(" => \"");
        try writeMessageFromCamel(w, field.name);
        try w.writeAll("\",\n");
    }

    for (def.error_suffix) |entry| {
        try renderZigErrorMessageCase(w, entry.zig_name, entry.message);
    }

    try w.writeAll(
        \\        else => "unknown error",
        \\    };
        \\}
        \\
        \\
    );
}

fn renderZigErrorMessageCase(w: *std.Io.Writer, zig_name: []const u8, message: []const u8) !void {
    try w.print("        .{s} => \"", .{zig_name});
    try std.zig.stringEscape(message, w);
    try w.writeAll("\",\n");
}

fn renderMapLibraryError(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\pub fn mapLibraryError(err: anyerror) ?zfh_error {
        \\
    );
    inline for (std.meta.fields(zfh.Error)) |field| {
        try w.print("    if (err == zfh.Error.{f}) return .", .{std.zig.fmtId(field.name)});
        try writeSnake(w, field.name, .lower, .camel);
        try w.writeAll(";\n");
    }
    try w.writeAll(
        \\    return null;
        \\}
        \\
    );
}
