const std = @import("std");
const zfh = @import("zig_files_hash");
const def = @import("def.zig");
const common = @import("common.zig");

const writeSnake = common.writeSnake;

pub fn render(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\/* Generated by tools/c_api/gen.zig. Do not edit by hand. */
        \\#ifndef ZIG_FILES_HASH_C_API_GENERATED_H
        \\#define ZIG_FILES_HASH_C_API_GENERATED_H
        \\
    );
    try w.print("#define ZFH_API_VERSION {d}u\n\n", .{def.api_version});

    try renderCErrorEnum(w);
    try renderCAlgorithmEnum(w);
    try renderCOptionFlags(w);

    try w.writeAll(
        \\#endif /* ZIG_FILES_HASH_C_API_GENERATED_H */
        \\
    );
}

fn renderCErrorEnum(w: *std.Io.Writer) !void {
    try w.writeAll("/* ABI note: enum numeric values are generated from ZFH_API_VERSION's C ABI contract. */\n");
    try w.writeAll("typedef enum zfh_error {\n");

    for (def.error_prefix, 0..) |entry, value| {
        try w.print("    {s} = {d},\n", .{ entry.c_name, value });
    }

    inline for (std.meta.fields(zfh.Error), 0..) |field, i| {
        try w.writeAll("    ZFH_");
        try writeSnake(w, field.name, .upper, .camel);
        try w.print(" = {d},\n", .{def.error_prefix.len + i});
    }

    const suffix_offset = def.error_prefix.len + std.meta.fields(zfh.Error).len;
    for (def.error_suffix, 0..) |entry, i| {
        try w.print("    {s} = {d},\n", .{ entry.c_name, suffix_offset + i });
    }

    try w.writeAll("} zfh_error;\n\n");
}

fn renderCAlgorithmEnum(w: *std.Io.Writer) !void {
    try w.writeAll("/* ABI note: enum numeric values are generated from ZFH_API_VERSION's C ABI contract. */\n");
    try w.writeAll("typedef enum zfh_algorithm {\n");
    inline for (std.meta.fields(zfh.HashAlgorithm), 0..) |field, value| {
        try w.writeAll("    ZFH_ALG_");
        try writeSnake(w, field.name, .upper, .separators);
        try w.print(" = {d},\n", .{value});
    }
    try w.writeAll("} zfh_algorithm;\n\n");
}

fn renderCOptionFlags(w: *std.Io.Writer) !void {
    try w.writeAll("enum {\n");
    for (def.option_flags) |entry| {
        try w.print("    {s} = {s},\n", .{ entry.c_name, entry.expr });
    }
    try w.writeAll("};\n\n");
}
