// Generated by tools/c_api/gen.zig. Do not edit by hand.
const zfh = @import("root.zig");

pub const ZFH_API_VERSION: u32 = 3;

pub const zfh_error = enum(c_int) {
    ok = 0,
    invalid_argument = 1,
    invalid_algorithm = 2,
    key_required = 3,
    invalid_key_length = 4,
    output_buffer_too_small = 5,
    operation_canceled = 6,
    invalid_state = 7,
    file_not_found = 8,
    access_denied = 9,
    invalid_path = 10,
    io_error = 11,
    unknown_error = 12,
    _,
};

pub const zfh_algorithm = enum(c_int) {
    sha_224 = 0,
    sha_256 = 1,
    sha_384 = 2,
    sha_512 = 3,
    sha_512_224 = 4,
    sha_512_256 = 5,
    md5 = 6,
    sha_1 = 7,
    xxh3_64 = 8,
    blake3 = 9,
    hmac_sha_224 = 10,
    hmac_sha_256 = 11,
    hmac_sha_384 = 12,
    hmac_sha_512 = 13,
    hmac_md5 = 14,
    hmac_sha_1 = 15,
    _,
};

pub const ZFH_OPTION_HAS_SEED: u32 = 1 << 0;
pub const ZFH_OPTION_HAS_KEY: u32 = 1 << 1;

pub fn toHashAlgorithm(alg: zfh_algorithm) ?zfh.HashAlgorithm {
    return switch (alg) {
        .sha_224 => .@"SHA-224",
        .sha_256 => .@"SHA-256",
        .sha_384 => .@"SHA-384",
        .sha_512 => .@"SHA-512",
        .sha_512_224 => .@"SHA-512/224",
        .sha_512_256 => .@"SHA-512/256",
        .md5 => .MD5,
        .sha_1 => .@"SHA-1",
        .xxh3_64 => .@"XXH3-64",
        .blake3 => .BLAKE3,
        .hmac_sha_224 => .@"HMAC-SHA-224",
        .hmac_sha_256 => .@"HMAC-SHA-256",
        .hmac_sha_384 => .@"HMAC-SHA-384",
        .hmac_sha_512 => .@"HMAC-SHA-512",
        .hmac_md5 => .@"HMAC-MD5",
        .hmac_sha_1 => .@"HMAC-SHA-1",
        else => null,
    };
}

pub fn errorMessage(code: zfh_error) [*:0]const u8 {
    return switch (code) {
        .ok => "ok",
        .invalid_argument => "invalid argument",
        .invalid_algorithm => "invalid algorithm",
        .key_required => "key required",
        .invalid_key_length => "invalid key length",
        .output_buffer_too_small => "output buffer too small",
        .operation_canceled => "operation canceled",
        .invalid_state => "invalid state",
        .file_not_found => "file not found",
        .access_denied => "access denied",
        .invalid_path => "invalid path",
        .io_error => "io error",
        .unknown_error => "unknown error",
        else => "unknown error",
    };
}

pub fn mapLibraryError(err: anyerror) ?zfh_error {
    if (err == zfh.Error.KeyRequired) return .key_required;
    if (err == zfh.Error.InvalidKeyLength) return .invalid_key_length;
    if (err == zfh.Error.OutputBufferTooSmall) return .output_buffer_too_small;
    if (err == zfh.Error.OperationCanceled) return .operation_canceled;
    if (err == zfh.Error.InvalidState) return .invalid_state;
    return null;
}
