/* Generated by tools/c_api/gen.zig. Do not edit by hand. */
#ifndef ZIG_FILES_HASH_C_API_GENERATED_H
#define ZIG_FILES_HASH_C_API_GENERATED_H
#define ZFH_API_VERSION 3u

/* ABI note: enum numeric values are generated from ZFH_API_VERSION's C ABI contract. */
typedef enum zfh_error {
    ZFH_OK = 0,
    ZFH_INVALID_ARGUMENT = 1,
    ZFH_INVALID_ALGORITHM = 2,
    ZFH_KEY_REQUIRED = 3,
    ZFH_INVALID_KEY_LENGTH = 4,
    ZFH_OUTPUT_BUFFER_TOO_SMALL = 5,
    ZFH_OPERATION_CANCELED = 6,
    ZFH_INVALID_STATE = 7,
    ZFH_FILE_NOT_FOUND = 8,
    ZFH_ACCESS_DENIED = 9,
    ZFH_INVALID_PATH = 10,
    ZFH_IO_ERROR = 11,
    ZFH_UNKNOWN_ERROR = 12,
} zfh_error;

/* ABI note: enum numeric values are generated from ZFH_API_VERSION's C ABI contract. */
typedef enum zfh_algorithm {
    ZFH_ALG_SHA_224 = 0,
    ZFH_ALG_SHA_256 = 1,
    ZFH_ALG_SHA_384 = 2,
    ZFH_ALG_SHA_512 = 3,
    ZFH_ALG_SHA_512_224 = 4,
    ZFH_ALG_SHA_512_256 = 5,
    ZFH_ALG_MD5 = 6,
    ZFH_ALG_SHA_1 = 7,
    ZFH_ALG_XXH3_64 = 8,
    ZFH_ALG_BLAKE3 = 9,
    ZFH_ALG_HMAC_SHA_224 = 10,
    ZFH_ALG_HMAC_SHA_256 = 11,
    ZFH_ALG_HMAC_SHA_384 = 12,
    ZFH_ALG_HMAC_SHA_512 = 13,
    ZFH_ALG_HMAC_MD5 = 14,
    ZFH_ALG_HMAC_SHA_1 = 15,
} zfh_algorithm;

enum {
    ZFH_OPTION_HAS_SEED = 1 << 0,
    ZFH_OPTION_HAS_KEY = 1 << 1,
};

#endif /* ZIG_FILES_HASH_C_API_GENERATED_H */
